version: '3.9'

services:
  db:
    image: mariadb:10.5
    restart: always
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  db_data: